---

classes:
  - exercises:
      - title: Getting started
        file: ../doc/workbook/public/01_getting_started.md
      - title: Workspace
        file: ../doc/workbook/public/02_workspace.md
      - title: Components
        file: ../doc/workbook/public/03_components.md
      - title: Unit testing
        file: ../doc/workbook/public/04_testing.md
      - title: Control flow
        file: ../doc/workbook/public/05_control_flow.md
      - title: Directives
        file: ../doc/workbook/public/06_directives.md
      - title: Signals
        file: ../doc/workbook/public/07_signals.md
      - title: Dependency injection
        file: ../doc/workbook/public/08_dependency_injection.md
      - title: Pipes
        file: ../doc/workbook/public/09_pipes.md
      - title: Http
        file: ../doc/workbook/public/10_http_client.md
      - title: Router
        file: ../doc/workbook/public/11_routing.md
      - title: Forms
        file: ../doc/workbook/public/12_forms.md
